version: '3'
services:
    # Mercury:
    #     image: milkyway_mercury:latest
        # build: .
    venus:
        # Tracking
        build: Venus/.Depoyment
        # volumes:
        #   - ./Venus/tracking/:/usr/share/nginx/html/tracking/
    earth:
        # Landing
        build:
          context: Earth/
          dockerfile: .Infrastructure/Docker/Development/Dockerfile
        volumes:
          - ./Earth:/app
        working_dir: /app
        command: npm run dev
    mars:
        # Assets
        build: Mars/.Depoyment
        volumes:
          - ./Mars/assets/:/usr/share/nginx/html/assets/
    # Ceres:
    #     image: milkyway_ceres:latest
        # build: .
    jupiter:
        # Proxy
        build: Jupiter/.Depoyment
        volumes:
          - ./Jupiter/proxy/proxy.conf:/etc/nginx/conf.d/proxy.conf
        ports:
          - "80:80"
    # Saturn:
    #     image: milkyway_saturn:latest
        # build: .
    # Uranus:
    #     image: milkyway_uranus:latest
        # build: .
    # Neptune:
    #     image: milkyway_neptune:latest
        # build: .
    pluto:
        build: Pluto/.Depoyment
        volumes:
          - ./Pluto/footer/:/usr/share/nginx/html/footer/
