name: "Version"

on:
  push:
    branches:
      - "release/**"

jobs:
  bump-version:
    name: "Version"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@master"
        with:
          ref: ${{ github.ref }}
      - name: "Submodules"
        uses: snickerbockers/submodules-init@v4
      - name: Increment version
        id: version   
        uses: vinodhraj/Bump-N-Tag-Version@master
        with:
          file_name: './VERSION'
          tag_version: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
