name: "Version"	

on:	
  push:	
    branches:	
      - "master"	   
      - "release"	
      - "release/**"	

jobs:	
  bump-version:	
    name: "Version"	
    runs-on: ubuntu-latest	
    steps:	
      - name: "Checkout source code"	
        uses: "actions/checkout@master"	
        with:	
          ref: ${{ github.ref }}	
      - name: "Submodules"	
        uses: snickerbockers/submodules-init@v4	
      - name: Version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
